apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .JobName }}"
  namespace: "{{ .ApplicationNamespace }}"
  labels:
    app: builder
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: buildkit
        image: moby/buildkit:master
        command:
        - buildctl-daemonless.sh
        args: ["build", "--frontend", "dockerfile.v0", "--local", "context=/workspace/build", "--local", "{{if .SubContext }}dockerfile=/workspace/build/{{.SubContext}}{{else}}dockerfile=/workspace/build{{end}}", "--output", "type=image,name={{ .ImageDestination }},push=true,registry.insecure=true"]
        volumeMounts:
        - name: build-context
          mountPath: /workspace
        securityContext:
          privileged: true
      initContainers:
      - name: git-sync
        image: k8s.gcr.io/git-sync:v3.1.6
        imagePullPolicy: Always
        volumeMounts:
        - name: build-context
          mountPath: /workspace
        - name: git-secret
          mountPath: /etc/git-secret
        env:
        - name: GIT_SYNC_REPO
          value: "{{ .SCMRepoURL }}"
        - name: GIT_SYNC_BRANCH
          value: master
        - name: GIT_SYNC_ROOT
          value: /workspace
        - name: GIT_SYNC_DEST
          value: build
        - name: GIT_SYNC_PERMISSIONS
          value: "0777"
        - name: GIT_SYNC_ONE_TIME
          value: "true"
        - name: GIT_SYNC_SSH
          value: "true"
        - name: GIT_KNOWN_HOSTS
          value: "true"
        securityContext:
          runAsUser: 0
      volumes:
      - name: build-context
        emptyDir: {}
      - name: git-secret
        secret:
          defaultMode: 256
          secretName: "{{ .SCMSecret }}"
