# permissions for end users to view cibuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cibuild-viewer-role
rules:
- apiGroups:
  - cicd.cicd.com
  resources:
  - cibuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cicd.cicd.com
  resources:
  - cibuilds/status
  verbs:
  - get
